footer:
  framework: Framework
  theme: Theme

copy:
  success: Copy successed!!
  error: Copy error ;-;
  noSupport: The browser does not support

page:
  articles: Articles
  tag: Tag
  category: Category
  archives: Archives

card_post_count: comments

sticky: Sticky
no_title: No title

post:
  created: Created
  updated: Updated
  wordcount: Word count
  min2read: Reading time
  min2read_unit: min
  page_pv: Post View
  comments: Comments
  copyright:
    author: Author
    link: Link
    copyright_notice: Copyright Notice
    copyright_content: 'All articles in this blog are basically licensed under <a href="%s">%s</a>. That is, you don&apos;t need to mark the author in general. The same license should be applied only when you secondarily process and share the work.'
  recommend: Related Articles
  edit: Edited on

search:
  title: Search
  load_data: Loading the Database
  algolia_search:
    input_placeholder: Search for Posts
    hits_empty: "We didn't find any results for the search: ${query}."
    hits_stats: '${hits} results found in ${time} ms'

  local_search:
    label: Local search
    input_placeholder: Search for Posts
    hits_empty: "We didn't find any results for the search: ${query}"

pagination:
  prev: Previous Post
  next: Next Post

comment: Comment

aside:
  articles: Articles
  tags: Tags
  categories: Categories
  card_announcement: Announcement
  card_categories: Categories
  card_tags: Tags
  card_archives: Archives
  card_recent_post: Recent Post
  card_webinfo:
    headline: Info
    article_name: Article
    runtime:
      name: Run time
      unit: days
    last_push_date:
      name: Last Push
    site_wordcount: Total Count
    site_uv_name: UV
    site_pv_name: PV
  more_button: More
  card_newest_comments:
    headline: Newest Comments
    loading_text: loading...
    error: Unable to get the data, please make sure the settings are correct.
    zero: No Comment
    image: image
    link: link
    code: code
  card_toc: Catalog

date_suffix:
  just: Just
  min: minutes ago
  hour: hours ago
  day: days ago
  month: months ago

donate: Donate
share: Share

rightside:
  readmode_title: Read Mode
  translate_title: Traditional Chinese / Simplified Chinese
  night_mode_title: Light Mode / Dark Mode
  back_to_top: Back To Top
  toc: Table Of Contents
  scroll_to_comment: Scroll To Comments
  setting: Display Settings
  aside: Single-column / Double-column
  chat: Chat

copy_copyright:
  author: Author
  link: Link
  source: Source
  info: Attribution-ShareAlike (https://creativecommons.org/licenses/by-sa/4.0/deed.en)

Snackbar:
  chs_to_cht: Traditional Chinese Activated
  cht_to_chs: Simplified Chinese Activated
  day_to_night: Dark Mode Activated
  night_to_day: Light Mode Activated

loading: Loading ...

error404: Page not found